### ISSUE TITLE
Program Review

### ISSUE THREAD

**Issue by jerseymason** [liaozhuzhu/TikTokQuoteVideoGenerator#1]
Hi, thank you for the such great program. 
Wanna ask about any idea how to create some bulk video at one process ? maybe automatic set to 10 videos to generate and the file name will be final.mp4 , final1.mp4 , and so on.

Thank you.

**Comment by liaozhuzhu** [comment]
Hi @jerseymason ,

Thanks for issuing this review. This is a great idea to implement. For now I've made it generate 5 videos using a normal for loop (I think 10 might be too many).

Thank you,
Liao
